#!/system/bin/sh
#Created by Team Acid
#Internal2External script

VAR=$(ls -l /dev/block/vold/ | sort | tail -1)

# Look for /mnt or /storage
if [ ! -e /storage/sdcard0/i2e ]; then
mount -t vfat -o umask=0000 echo "$VAR" > /dev/block/vold/ /storage/sdcard0 

mount -o bind /data/media /storage/sdcard1   
else
echo Not Found
fi

if [ ! -e /mnt/sdcard/i2e ]; then
mount -t vfat -o umask=0000 echo "$VAR" /dev/block/vold/ /mnt/sdcard 

mount -o bind /data/media /mnt/extSdCard   
else
echo Not Found
fi


