#!/system/bin/sh
#Created by Team Acid
#Internal2External script

CD /dev/block/vold/


VAR=$(ls -d /dev/block/vold/* | tail -1)

echo $VAR



# Look for /mnt or /storage
if (find /storage -name sdcard0); then

mount -t vfat -o umask=0000 $VAR storage/sdcard0 

mount -o bind /data/media /storage/sdcard1   
fi

if (find /mnt -name extSdCard); then

mount -t fat -o unmask=0000 $VAR mnt/sdcard

mount -o bind /data/media /mnt/extSdCard
fi

