#!/system/bin/sh
#Created by Team Acid
#Internal2External script

VAR=$(ls -l /dev/block/vold/ | sort | tail -1)

# Look for /mnt or /storage
if [ find / -name storage ]; then
mount -t vfat -o umask=0000  /dev/block/vold/ /storage/sdcard0 

mount -o bind /data/media /storage/sdcard1   

fi


