#!/system/bin/sh
#created by Team Acid

timeout=100000

while : ; do
    awake=(cat /sys/power/wait_for_fb_wake)

    if ($awake = "awake"); then
		chmod 666 /sys/devices/system/cpu/cpu1/online
		usleep $timeout
		echo "1" > /sys/devices/system/cpu/cpu1/online
endif;

sleep=(cat /sys/power/wait_for_fb_sleep)

    if ($sleep = "sleeping"); then
		chmod 666 /sys/devices/system/cpu/cpu1/online
		usleep $timeout
		echo "0" > /sys/devices/system/cpu/cpu1/online
endif;
		
    if (find /sys/devices/system/cpu -name cpu2); then
	    if ($awake = "awake"); then
		usleep $timeout
		echo "1" > /sys/devices/system/cpu/cpu2/online
endif;

    if (find /sys/devices/system/cpu -name cpu2); then
	    if ($sleep = "sleeping"); then
		usleep $timeout
		echo "0" > /sys/devices/system/cpu/cpu2/online
endif;

    if (find /sys/devices/system/cpu -name cpu2); then
	    if ($awake = "awake"); then
		usleep $timeout
		echo "1" > /sys/devices/system/cpu/cpu2/online
endif;

    if (find /sys/devices/system/cpu -name cpu3); then
	    if ($sleep = "sleeping"); then
		usleep $timeout
		echo "0" > /sys/devices/system/cpu/cpu3/online
endif;


