#!/system/bin/sh
#Created by Team Acid
#Internal2External script


VAR=$(ls -d /dev/block/vold/* | tail -1)

echo $VAR


mount -t vfat -o umask=0000 $VAR /storage/sdcard0 

mount -o bind /data/media /storage/sdcard0   


