#!/system/bin/sh
#Remove buildpropext script for no overflow on buildprop

if(find /system/etc/init.d -name 74buildproprm); then
rm /system/etc/init.d/74buildproprm
done

if(find /system/etc/init.d -name 76journalrm); then
rm /system/etc/init.d/76journalrm
done

